version: "3.9"

services:
  # --- API Gateway ---
  api-gateway:
    build: 
      context: ./api_gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api_gateway/.env.docker
    depends_on:
      - auth-service
      - user-service
      - company-service
      - job-service
      - application-service
    networks:
      - hiring-network

  # --- Auth Service ---
  auth-service:
    build: 
      context: ./auth_service
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./auth_service/.env.docker
    depends_on:
      - auth-db
    networks:
      - hiring-network

  auth-db:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_db
    ports:
      - "5431:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - hiring-network

  # --- User Service ---
  user-service:
    build: 
      context: ./user_service
    container_name: user-service
    ports:
      - "8002:8002"
    env_file:
      - ./user_service/.env.docker
    depends_on:
      - user-db
    networks:
      - hiring-network

  user-db:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_user_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - hiring-network

  # --- Company Service ---
  company-service:
    build: 
      context: ./company_service
    container_name: company-service
    ports:
      - "8003:8003"
    env_file:
      - ./company_service/.env.docker
    depends_on:
      - company-db
    networks:
      - hiring-network

  company-db:
    image: postgres:15
    container_name: company-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_company_db
    ports:
      - "5433:5432"
    volumes:
      - company_db_data:/var/lib/postgresql/data
    networks:
      - hiring-network

  # --- Job Service ---
  job-service:
    build: 
      context: ./job_service
    container_name: job-service
    ports:
      - "8005:8005"
    env_file:
      - ./job_service/.env.docker
    depends_on:
      - job-db
    networks:
      - hiring-network

  job-db:
    image: postgres:15
    container_name: job-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_job_db
    ports:
      - "5434:5432"
    volumes:
      - job_db_data:/var/lib/postgresql/data
    networks:
      - hiring-network

  # --- Application Service ---
  application-service:
    build: 
      context: ./application_service
    container_name: application-service
    ports:
      - "8004:8004"
    env_file:
      - ./application_service/.env.docker
    depends_on:
      - application-db
    networks:
      - hiring-network

  application-db:
    image: postgres:15
    container_name: application-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_apply_db
    ports:
      - "5436:5432"
    volumes:
      - application_db_data:/var/lib/postgresql/data
    networks:
      - hiring-network

volumes:
  auth_db_data:
  user_db_data:
  company_db_data:
  job_db_data:
  application_db_data:

networks:
  hiring-network:
    driver: bridge
