version: "3.9"
 
services:
 
  company-service:
    build: .
    container_name: company-service
    ports:
      - "8003:8003"
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - auth-network
 
  db:
    image: postgres:15
    container_name: company-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_company_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
 
volumes:
  postgres_data:
 
networks:
  auth-network:
 