version: "3.9"
 
services:
 
  job-service:
    build: .
    container_name: job-service
    ports:
      - "8005:8005"
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - job-network
 
  db:
    image: postgres:15
    container_name: job-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservice_job_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-network
 
volumes:
  postgres_data:
 
networks:
  job-network:
 